version: '3.8'
services:
  web:
    image: ddulaev/lab3:latest
    container_name: web
    depends_on:
      - db
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
    build:
      dockerfile: DockerfileModel
    command: bash -c "python src/images_dataset.py && python src/img_with_name_dataloader.py && coverage run -a src/unit_tests/test_hog_embeddings.py && coverage report -m --ignore-errors"
    ports:
      - "8000:8000"

  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    volumes:
      - db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - "5432:5432"
    restart: on-failure

volumes:
  db-data:
